[package]
name = "net-filter-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.44.2", features = ["fs"] }
